apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: "vault:0.10.3"
          imagePullPolicy: Always
        - name: vault-go
          image: "vault-go:v1"
          imagePullPolicy: Never
